#!/usr/bin/env bash
set -euo pipefail

ENV_FILE=".env"

echo "======================================="
echo "  Stream Media - Initial Setup"
echo "======================================="
echo

# ── Admin User ──

echo "-- Admin Account --"
echo

read -rp "Admin username: " ADMIN_USERNAME
read -rp "Admin email: " ADMIN_EMAIL

while true; do
    read -rsp "Admin password: " ADMIN_PASSWORD
    echo
    read -rsp "Confirm password: " ADMIN_PASSWORD_CONFIRM
    echo

    if [ "$ADMIN_PASSWORD" = "$ADMIN_PASSWORD_CONFIRM" ]; then
        break
    fi
    echo "Passwords do not match. Try again."
    echo
done

echo

# ── Streaming Method ──

echo "-- Streaming Method --"
echo
echo "  1) HLS  - Adaptive bitrate streaming (recommended)"
echo "     Videos are transcoded into multiple quality levels."
echo "     Players automatically switch quality based on network speed."
echo
echo "  2) DASH - Dynamic Adaptive Streaming over HTTP"
echo "     Similar to HLS but uses the MPEG-DASH standard."
echo "     (not yet implemented - will fall back to HTTP range)"
echo
echo "  3) HTTP Range - Direct file streaming"
echo "     Serves the original file as-is with byte-range support."
echo "     No transcoding. Simplest option."
echo

while true; do
    read -rp "Select streaming method [1/2/3]: " STREAM_CHOICE
    case "$STREAM_CHOICE" in
        1) STREAMING_METHOD="hls";   break ;;
        2) STREAMING_METHOD="dash";  break ;;
        3) STREAMING_METHOD="range"; break ;;
        *) echo "Invalid choice. Enter 1, 2, or 3." ;;
    esac
done

echo

# ── Write .env ──

cat > "$ENV_FILE" <<EOF
# Stream Media configuration - generated by setup.sh

# Admin credentials (used to seed admin user on first boot)
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Streaming method: hls, dash, or range
STREAMING_METHOD=${STREAMING_METHOD}
EOF

chmod 600 "$ENV_FILE"

echo "======================================="
echo "  Setup complete!"
echo "======================================="
echo
echo "  Admin user:       $ADMIN_USERNAME"
echo "  Streaming method: $STREAMING_METHOD"
echo "  Config written to: $ENV_FILE"
echo
echo "  Start the services with:"
echo "    docker compose up -d"
echo
echo "  Or run locally:"
echo "    source .env && cargo run -p gateway &"
echo "    source .env && cargo run -p catalog-service &"
echo "    source .env && cargo run -p streaming-service &"
echo "    source .env && cargo run -p user-service &"
echo
